import { database } from 'config/firebase-config'
import Head from 'next/head'
import Link from 'next/link'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Anonymous Random Confessions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1 className='main-title'>Anonymous Random confessions...</h1> 
        <section className='category-links'>
          {
            data?.map((btn, i) => 
              <Link key={i} href={`/${btn.id}`} className='link'>
                {btn.title}
              </Link>
            )
          }
        </section>
      </main>
    </>
  )
}

export async function getServerSideProps () {
  //I am suing the data.json data since categories arent the much, plus its unecessary...
  //const {categories} = await import("/data/data.json")
  const docRef = doc(database, "categories");
  const data = await getDoc(docRef);
  const categories = data.docs.map(doc => doc.data())

  return {
    props: { 
      data: categories
    }
  }
}