//Next.jS...
import Head from 'next/head'
import Link from 'next/link'

//FIrebase...
import { auth } from 'config/firebase-config'
import {useAuthState} from "react-firebase-hooks/auth"
import {signOut} from "firebase/auth"


export default function Home({data}) {
  const [user] = useAuthState(auth)

  const userSignOut = async () => {
    await signOut(auth)
  }

  return (
    <>
      <Head>
        <title>Anonymous Random Confessions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1 className='main-title'>Anonymous Random confessions...</h1> 
        <section className='category-links'>
          {
            data?.map((btn, i) => 
              <Link key={i} href={`/${btn.id}`} className='link'>
                {btn.title}
              </Link>
            )
          }
        </section>
        {!user && <Link className='login-btn' href="/login">Login</Link>}
        {user && <button onClick={userSignOut} className='login-btn' href="/login">Log-out</button>}
      </main>
    </>
  )
}

export async function getStaticProps () {
  //I am suing the data.json data since categories arent the much, plus its unecessary...
  const {categories} = await import("/data/data.json");

  return {
    props: { 
      data: categories
    }
  }
}