import Head from 'next/head'
import Link from 'next/link'



export default function Home({data}) {

  return (
    <>
      <Head>
        <title>To do list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1 className='main-title'>Random confessions...</h1>
        <section className='category-links'>
          {
            data?.map(btn => 
              <Link href={`/${btn.id}`} className='link'>
                {btn.title}
              </Link>
            )
          }
        </section>

      </main>
    </>
  )
}

export async function getServerSideProps () {
  const {categories} = await import("/data/data.json")

  console.log(categories)

  return {
    props: { 
      data: categories
    }
  }
}